Navbar and posts page
qmfkdldks/visible-idea-landing pull request #1
Opened 2022-02-03 20:10 UTC by IanMuler

# Navbar

# What
User should be able to navigate through the navbar.
There should be two links in the navbar.

https://github.com/qmfkdldks/portfolio

# Acceptance Criteria

- Add navbar  component
- Add "Home" and "Posts" links
- Home link should navigate to home page
- Post link should navigate to posts page
- Should work in mobile version

# Post Page

# What
Build a new posts page with a list of sample links
Currently, we have not defined how to get link items data.
It is ok to make false lists at this moment.

# Acceptance Criteria

- Add link component
- Add posts page
- Add route https://localhost:3000/posts  should render posts page

2022-02-03 23:27 UTC, qmfkdldks requested changes

2022-02-03 23:27 UTC, qmfkdldks commented on package.json
> +    "@styled-icons/heroicons-outline": "^10.36.0",
:+1:

2022-02-03 23:27 UTC, qmfkdldks commented on pages/home/layers/navbar/component.tsx
> +};
En vez de implementar así
Estaría bueno renombrar sidebar por navbar

2022-02-03 23:27 UTC, qmfkdldks commented on styles/globals.css
> +a, a:visited, a:hover, a:active {
Para qué es necesario ser estilo global?

2022-02-03 23:27 UTC, qmfkdldks commented on pages/home/index.tsx
> +        <Navbar offset={0} speed={-0.1} isTabletOrMobile={isTabletOrMobile} />
Navbar debería estar fuera de Parallax component.
Parallax es para scroll animation.
Si es posible, puedes mover para que este más arriba?

2022-02-03 23:27 UTC, qmfkdldks commented on components/sidebar/__tests__/component.cypress.tsx
> +// import { mount } from "@cypress/react";
Puedes descomentar el archivo.

2022-02-04 19:54 UTC, IanMuler commented on styles/globals.css
> +a, a:visited, a:hover, a:active {
No es necesario, ahora lo borro

2022-02-08 17:17 UTC, qmfkdldks approved these changes

2022-02-08 20:56 UTC, merged